@startuml

class GameLogic {
  - BOARD_ROW: const int
  - BOARD_COL: const int
  - mCountRect1: const Gdiplus::RectF
  - mCountRect2: const Gdiplus::RectF
  - mWinnerRect: const Gdiplus::RectF
  - mBackground: std::unique_ptr<Gdiplus::Image>
  - mDeck: std::list<Card>
  - mClickCount: int
  - mHwnd: HWND
  - mpPrevious: Card*
  - mPlayerTurn: int
  - mPlayer1Scroe: int
  - mPlayer2Scroe: int

  + Init(hwnd: HWND): void
  + Release(): void
  + Draw(graphics: Gdiplus::Graphics): void
  + OnClick(x: int, y: int): void
  - CreateCards(): void
  - SwitchPlayerTurn() : void
}

class Card {
  - mBack: std::unique_ptr<Gdiplus::Image>
  - mFront: std::unique_ptr<Gdiplus::Image>
  - mX: int
  - mY: int
  - mIsFront: bool
  - mType: Type
  - mHwnd: HWND
  - mIndex: int

  + Card(hwnd: HWND, index: int, type: Type, x: int, y: int)
  + CheckClicked(x: int, y: int): bool
  + Flip(isFront: bool): void
  + Draw(graphics: Gdiplus::Graphics): void
  + Invalidate(): void
  + GetType(): Type
  + GetIndex(): int
}

GameLogic --|> Card

@enduml